# Workflow to learn about DevOps, GitHub Actions, and commands in .yml
name: devops-research-workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  setup-and-lint:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python and install Pylint
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      # Run Pylint and save the results
      - name: Run Pylint
        run: pylint . > pylint-report.txt
      - name: Upload Pylint report
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: pylint-report.txt

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      # Install and run tests
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  deploy-to-environment:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Deploy to a simulated environment
      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          echo "Deployment successful!"
